import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const schemes = [
    // ===== AGRICULTURE =====
    {
        title: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        department: "Department of Agriculture & Farmers Welfare",
        ministry: "Ministry of Agriculture",
        benefit: "Direct income support of ₹6,000 per year in 3 installments",
        benefitAmount: "₹6,000/year",
        category: ["Farmer", "Agriculture"],
        state: "All India",
        description: "Financial benefit to small and marginal farmer families with cultivable land holding. Amount is transferred directly to bank accounts.",
        eligibility: ["Small and marginal farmers with cultivable landholding", "Name must appear in land records", "Valid Aadhaar card linked to bank account"],
        documents: ["Aadhaar Card", "Land Ownership Documents", "Bank Account Details", "Mobile Number"],
        applicationLink: "https://pmkisan.gov.in",
        isCentral: true,
        maxIncome: 1000000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        department: "Department of Agriculture & Farmers Welfare",
        ministry: "Ministry of Agriculture",
        benefit: "Crop insurance at subsidized premium rates",
        benefitAmount: "Premium: 2% Kharif, 1.5% Rabi",
        category: ["Farmer", "Agriculture", "Insurance"],
        state: "All India",
        description: "Comprehensive crop insurance scheme providing financial support to farmers suffering crop loss due to natural calamities, pests, and diseases.",
        eligibility: ["All farmers including sharecroppers and tenant farmers", "Crops notified by state", "Must insure entire area under notified crop"],
        documents: ["Aadhaar Card", "Land Records", "Bank Account", "Sowing Certificate"],
        applicationLink: "https://pmfby.gov.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Kisan Credit Card (KCC)",
        department: "Department of Agriculture & Farmers Welfare",
        ministry: "Ministry of Agriculture",
        benefit: "Short-term credit for crop production at 4% interest",
        benefitAmount: "Up to ₹3,00,000 at 4% p.a.",
        category: ["Farmer", "Agriculture", "Loan"],
        state: "All India",
        description: "Provides adequate and timely credit to farmers for their agricultural and allied activities at subsidized interest rates.",
        eligibility: ["Individual farmers (owner cultivators)", "Tenant farmers / sharecroppers", "Self Help Groups or Joint Liability Groups"],
        documents: ["Aadhaar Card", "Land Records", "Passport Size Photo", "Bank Account"],
        applicationLink: "https://pmkisan.gov.in/kcc",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Soil Health Card Scheme",
        department: "Department of Agriculture & Farmers Welfare",
        ministry: "Ministry of Agriculture",
        benefit: "Free soil testing and nutrient-based recommendations",
        benefitAmount: "Free service",
        category: ["Farmer", "Agriculture"],
        state: "All India",
        description: "Provides soil health cards to farmers carrying crop-wise recommendations of nutrients and fertilizers for improved productivity.",
        eligibility: ["All farmers across India", "Must have cultivable land"],
        documents: ["Aadhaar Card", "Land Records"],
        applicationLink: "https://soilhealth.dac.gov.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== HEALTH =====
    {
        title: "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PMJAY)",
        department: "National Health Authority",
        ministry: "Ministry of Health & Family Welfare",
        benefit: "Health insurance cover of ₹5 lakh per family per year",
        benefitAmount: "₹5,00,000/year",
        category: ["Health", "Insurance", "BPL"],
        state: "All India",
        description: "World's largest health insurance scheme providing cashless and paperless access to health services for the bottom 40% of the population.",
        eligibility: ["Families identified under SECC database", "No restrictions on family size, age, or gender", "Covers pre-existing conditions from day one"],
        documents: ["Aadhaar Card", "Ration Card", "SECC Database Inclusion Proof"],
        applicationLink: "https://pmjay.gov.in",
        isCentral: true,
        maxIncome: 300000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Janani Suraksha Yojana (JSY)",
        department: "Ministry of Health & Family Welfare",
        ministry: "Ministry of Health & Family Welfare",
        benefit: "Cash assistance for institutional delivery",
        benefitAmount: "₹1,400 (Rural), ₹1,000 (Urban)",
        category: ["Health", "Women", "Maternity"],
        state: "All India",
        description: "Safe motherhood intervention promoting institutional delivery among pregnant women, especially in low-performing states.",
        eligibility: ["Pregnant women above 19 years of age", "BPL families", "SC/ST women", "Up to 2 live births"],
        documents: ["Aadhaar Card", "BPL Certificate", "Pregnancy Registration", "Bank Account"],
        applicationLink: "https://nhm.gov.in",
        isCentral: true,
        minAge: 19,
        maxIncome: 200000,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Pradhan Mantri Surakshit Matritva Abhiyan",
        department: "Ministry of Health & Family Welfare",
        ministry: "Ministry of Health & Family Welfare",
        benefit: "Free antenatal care on 9th of every month",
        benefitAmount: "Free consultation & check-ups",
        category: ["Health", "Women", "Maternity"],
        state: "All India",
        description: "Provides free antenatal care to pregnant women on the 9th of every month at government health facilities.",
        eligibility: ["All pregnant women in their 2nd/3rd trimester", "Services available at government health facilities"],
        documents: ["Aadhaar Card", "Pregnancy Registration Card"],
        applicationLink: "https://pmsma.nhp.gov.in",
        isCentral: true,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Rashtriya Swasthya Bima Yojana (RSBY)",
        department: "Ministry of Labour & Employment",
        ministry: "Ministry of Labour & Employment",
        benefit: "Health insurance for BPL families",
        benefitAmount: "₹30,000/year per family",
        category: ["Health", "Insurance", "BPL", "Labour"],
        state: "All India",
        description: "Health insurance coverage for BPL families and unorganized sector workers with cashless treatment at empaneled hospitals.",
        eligibility: ["BPL families", "Unorganized sector workers", "Maximum 5 members per family"],
        documents: ["Aadhaar Card", "BPL Card", "Ration Card"],
        applicationLink: "https://www.rsby.gov.in",
        isCentral: true,
        maxIncome: 200000,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== EDUCATION =====
    {
        title: "National Scholarship Portal (NSP) - Post-Matric Scholarship",
        department: "Department of Social Justice & Empowerment",
        ministry: "Ministry of Social Justice & Empowerment",
        benefit: "Scholarships for SC/ST/OBC/Minority students",
        benefitAmount: "₹3,000 - ₹20,000/year",
        category: ["Education", "Student", "SC", "ST", "OBC"],
        state: "All India",
        description: "Financial assistance to students from disadvantaged communities pursuing post-matric education at recognized institutions.",
        eligibility: ["Students belonging to SC/ST/OBC/Minority communities", "Family income below ₹2.5 lakh per annum", "Enrolled in recognized post-matric course"],
        documents: ["Aadhaar Card", "Income Certificate", "Caste Certificate", "Previous Year Marksheet", "Admission Letter"],
        applicationLink: "https://scholarships.gov.in",
        isCentral: true,
        maxIncome: 250000,
        categoryReq: ["SC", "ST", "OBC", "Minority"],
        genderReq: "All",
    },
    {
        title: "Central Sector Scholarship for College and University Students",
        department: "Department of Higher Education",
        ministry: "Ministry of Education",
        benefit: "Merit-based scholarship for undergraduate/postgraduate students",
        benefitAmount: "₹10,000 - ₹20,000/year",
        category: ["Education", "Student"],
        state: "All India",
        description: "Scholarship for meritorious students from economically weaker sections to pursue higher education at recognized institutions.",
        eligibility: ["Scored above 80th percentile in Class XII board exam", "Family income below ₹8 lakh per annum", "Not receiving any other scholarship"],
        documents: ["Aadhaar Card", "Income Certificate", "Class XII Marksheet", "College Admission Proof", "Bank Account"],
        applicationLink: "https://scholarships.gov.in",
        isCentral: true,
        maxIncome: 800000,
        maxAge: 30,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pragati Scholarship for Girls",
        department: "AICTE",
        ministry: "Ministry of Education",
        benefit: "Scholarship for girls in technical education",
        benefitAmount: "₹50,000/year",
        category: ["Education", "Women", "Student"],
        state: "All India",
        description: "One girl per family studying in AICTE-approved institutions for degree/diploma courses in engineering and technology.",
        eligibility: ["Girl student admitted to AICTE-approved institution", "Family income below ₹8 lakh per annum", "One girl per family"],
        documents: ["Aadhaar Card", "Income Certificate", "Admission Letter", "10th & 12th Marksheets"],
        applicationLink: "https://www.aicte-india.org/schemes/students-development-schemes/pragati",
        isCentral: true,
        maxIncome: 800000,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Vidyalakshmi Education Loan Portal",
        department: "Department of Financial Services",
        ministry: "Ministry of Finance",
        benefit: "Education loans from multiple banks through single portal",
        benefitAmount: "Up to ₹20,00,000",
        category: ["Education", "Student", "Loan"],
        state: "All India",
        description: "Single-window portal for students to apply for education loans from multiple banks and for scholarship schemes.",
        eligibility: ["Indian nationals", "Admitted to recognized course in India or abroad", "Age typically below 35 years"],
        documents: ["Aadhaar Card", "Admission Letter", "Fee Structure", "Income Proof", "Academic Records"],
        applicationLink: "https://www.vidyalakshmi.co.in",
        isCentral: true,
        maxAge: 35,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "PM YASASVI - Scholarship for OBC/EBC/DNT Students",
        department: "Department of Social Justice & Empowerment",
        ministry: "Ministry of Social Justice & Empowerment",
        benefit: "Scholarship based on entrance test performance",
        benefitAmount: "₹75,000 - ₹1,25,000/year",
        category: ["Education", "Student", "OBC"],
        state: "All India",
        description: "Vibrant India scholarship for OBC, EBC, and DNT students studying in Class IX to XII and beyond.",
        eligibility: ["OBC/EBC/DNT category students", "Family income below ₹2.5 lakh per annum", "Must qualify PM YASASVI entrance test"],
        documents: ["Aadhaar Card", "OBC/EBC Certificate", "Income Certificate", "School ID", "Entrance Test Score"],
        applicationLink: "https://yet.nta.ac.in",
        isCentral: true,
        maxIncome: 250000,
        maxAge: 25,
        categoryReq: ["OBC"],
        genderReq: "All",
    },

    // ===== HOUSING =====
    {
        title: "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        department: "Ministry of Rural Development",
        ministry: "Ministry of Rural Development",
        benefit: "Financial assistance for pucca house construction in rural areas",
        benefitAmount: "₹1,20,000 (Plains) / ₹1,30,000 (Hilly)",
        category: ["Housing", "Rural", "BPL"],
        state: "All India",
        description: "Provides financial assistance to houseless and living in kutcha/dilapidated houses for construction of pucca houses with basic amenities.",
        eligibility: ["Houseless families or living in kutcha/dilapidated house", "No pucca house anywhere in India", "Should be in SECC-2011 deprivation list"],
        documents: ["Aadhaar Card", "Income Certificate", "BPL Card", "Land Documents", "Bank Account"],
        applicationLink: "https://pmayg.nic.in",
        isCentral: true,
        maxIncome: 300000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Awas Yojana - Urban (PMAY-U)",
        department: "Ministry of Housing & Urban Affairs",
        ministry: "Ministry of Housing & Urban Affairs",
        benefit: "Interest subsidy on home loans for urban housing",
        benefitAmount: "Subsidy up to ₹2,67,000",
        category: ["Housing", "Urban"],
        state: "All India",
        description: "Credit-linked subsidy for home purchase/construction/renovation in urban areas for EWS, LIG, MIG categories.",
        eligibility: ["No pucca house in any part of India", "EWS: Income up to ₹3 lakh", "LIG: Income ₹3-6 lakh", "MIG-I: Income ₹6-12 lakh"],
        documents: ["Aadhaar Card", "Income Certificate", "Property Documents", "Bank Account", "No-home Declaration"],
        applicationLink: "https://pmaymis.gov.in",
        isCentral: true,
        maxIncome: 1200000,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== EMPLOYMENT =====
    {
        title: "MGNREGA - Mahatma Gandhi National Rural Employment Guarantee",
        department: "Ministry of Rural Development",
        ministry: "Ministry of Rural Development",
        benefit: "100 days guaranteed wage employment per household per year",
        benefitAmount: "₹200-350/day (state-wise)",
        category: ["Employment", "Rural", "Labour"],
        state: "All India",
        description: "Legal guarantee of 100 days of wage employment in every financial year to adult members of rural households willing to do unskilled manual work.",
        eligibility: ["Adult members of rural households", "Willing to do unskilled manual work", "Registered with local Gram Panchayat"],
        documents: ["Job Card", "Aadhaar Card", "Bank Account Details"],
        applicationLink: "https://nrega.nic.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
        minAge: 18,
    },
    {
        title: "Pradhan Mantri Rozgar Protsahan Yojana (PMRPY)",
        department: "Ministry of Labour & Employment",
        ministry: "Ministry of Labour & Employment",
        benefit: "Government pays employer's EPF contribution for new employees",
        benefitAmount: "12% EPF contribution by Govt",
        category: ["Employment", "Business"],
        state: "All India",
        description: "Incentivizes employers for generating new employment by paying the employer's contribution to EPF for new employees.",
        eligibility: ["Establishment registered with EPFO", "New employee with salary up to ₹15,000/month", "Employee has valid UAN and Aadhaar"],
        documents: ["EPFO Registration", "Employee Aadhaar", "UAN Details", "Salary Slip"],
        applicationLink: "https://pmrpy.gov.in",
        isCentral: true,
        maxIncome: 180000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Deendayal Antyodaya Yojana - NULM",
        department: "Ministry of Housing & Urban Affairs",
        ministry: "Ministry of Housing & Urban Affairs",
        benefit: "Self-employment and skill training for urban poor",
        benefitAmount: "Subsidy up to ₹2,00,000",
        category: ["Employment", "Urban", "BPL", "Self-Employment"],
        state: "All India",
        description: "Reduces poverty and vulnerability of urban poor through gainful self-employment and skilled wage employment.",
        eligibility: ["Urban poor with family income below poverty line", "Women, SC/ST, minorities, disabled persons prioritized", "Age 18 years and above"],
        documents: ["Aadhaar Card", "Income Certificate", "Address Proof", "Bank Account"],
        applicationLink: "https://nulm.gov.in",
        isCentral: true,
        maxIncome: 200000,
        minAge: 18,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== WOMEN & CHILD =====
    {
        title: "Beti Bachao Beti Padhao",
        department: "Ministry of Women & Child Development",
        ministry: "Ministry of Women & Child Development",
        benefit: "Awareness and support for girl child welfare and education",
        benefitAmount: "Varies by state",
        category: ["Women", "Child", "Education"],
        state: "All India",
        description: "Addresses declining child sex ratio and promotes education and empowerment of girls.",
        eligibility: ["Girl children across India", "Families with girl children"],
        documents: ["Birth Certificate", "Aadhaar Card"],
        applicationLink: "https://wcd.nic.in/bbbp-schemes",
        isCentral: true,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Sukanya Samriddhi Yojana (SSY)",
        department: "Department of Economic Affairs",
        ministry: "Ministry of Finance",
        benefit: "High-interest savings for girl child education & marriage",
        benefitAmount: "8.2% interest rate",
        category: ["Women", "Child", "Savings"],
        state: "All India",
        description: "Small deposit scheme for girl child providing attractive interest rate and tax benefits under Section 80C.",
        eligibility: ["Girl child below 10 years of age", "Only one account per girl child", "Maximum two accounts per family"],
        documents: ["Girl's Birth Certificate", "Parent/Guardian ID Proof", "Address Proof"],
        applicationLink: "https://www.indiapost.gov.in",
        isCentral: true,
        maxAge: 10,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        department: "Ministry of Women & Child Development",
        ministry: "Ministry of Women & Child Development",
        benefit: "Maternity benefit for first live birth",
        benefitAmount: "₹5,000 in 3 installments",
        category: ["Women", "Maternity", "Health"],
        state: "All India",
        description: "Cash incentive for pregnant and lactating women for first living child to compensate wage loss and improve health seeking behavior.",
        eligibility: ["Pregnant and lactating women for first live birth", "Age 19 years and above", "Not employed in public sector"],
        documents: ["Aadhaar Card", "Bank Account", "MCP Card", "Pregnancy Registration"],
        applicationLink: "https://wcd.nic.in/schemes/pmmvy",
        isCentral: true,
        minAge: 19,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Mahila Shakti Kendra",
        department: "Ministry of Women & Child Development",
        ministry: "Ministry of Women & Child Development",
        benefit: "Skill development and employment for rural women",
        benefitAmount: "Free training & support",
        category: ["Women", "Rural", "Skill Development"],
        state: "All India",
        description: "Empowers rural women through community participation and awareness generation on government schemes.",
        eligibility: ["Rural women across India", "Priority to marginalized women"],
        documents: ["Aadhaar Card", "Address Proof"],
        applicationLink: "https://wcd.nic.in",
        isCentral: true,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Mukhyamantri Kanya Sumangala Yojana",
        department: "Women & Child Development",
        ministry: "Government of Uttar Pradesh",
        benefit: "Financial assistance of ₹15,000 in 6 installments",
        benefitAmount: "₹15,000 (in installments)",
        category: ["Women", "Child", "Education"],
        state: "Uttar Pradesh",
        description: "Financial support to girl child from birth to graduation in 6 equal installments tied to key milestones.",
        eligibility: ["Resident of Uttar Pradesh", "Family income less than ₹3 lakh per annum", "Maximum two girl children per family"],
        documents: ["Birth Certificate", "Income Certificate", "Bank Account", "Aadhaar"],
        applicationLink: "https://mksy.up.gov.in",
        isCentral: false,
        maxIncome: 300000,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Mukhyamantri Kanya Utthan Yojana",
        department: "Education Department",
        ministry: "Government of Bihar",
        benefit: "Financial assistance from birth to graduation for girls",
        benefitAmount: "Up to ₹54,100",
        category: ["Women", "Child", "Education"],
        state: "Bihar",
        description: "Comprehensive scheme for girl child empowerment through financial assistance at various stages from birth to graduation.",
        eligibility: ["Girl child born in Bihar", "Resident of Bihar", "Up to 2 daughters per family"],
        documents: ["Birth Certificate", "Aadhaar Card", "Bank Account", "Marksheets"],
        applicationLink: "https://edudbt.bih.nic.in",
        isCentral: false,
        genderReq: "Female",
        categoryReq: [],
    },

    // ===== FINANCE & LOANS =====
    {
        title: "Pradhan Mantri Mudra Yojana (PMMY)",
        department: "Department of Financial Services",
        ministry: "Ministry of Finance",
        benefit: "Collateral-free business loans up to ₹10 lakh",
        benefitAmount: "Up to ₹10,00,000",
        category: ["Business", "Self-Employment", "Loan"],
        state: "All India",
        description: "Provides loans to non-corporate, non-farm small/micro enterprises. Three categories: Shishu (up to ₹50K), Kishore (₹50K-5L), Tarun (₹5L-10L).",
        eligibility: ["Non-corporate, non-farm small/micro enterprises", "Manufacturing, trading, or service sector", "Indian citizen with business plan"],
        documents: ["Business Plan", "Aadhaar Card", "Identity Proof", "Address Proof", "Business Registration (if applicable)"],
        applicationLink: "https://www.mudra.org.in",
        isCentral: true,
        minAge: 18,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Stand Up India",
        department: "Department of Financial Services",
        ministry: "Ministry of Finance",
        benefit: "Bank loans for SC/ST and women entrepreneurs",
        benefitAmount: "₹10 lakh to ₹1 crore",
        category: ["Business", "Women", "SC", "ST", "Loan"],
        state: "All India",
        description: "Facilitates bank loans between ₹10 lakh and ₹1 crore to at least one SC/ST and one women borrower per bank branch for greenfield enterprises.",
        eligibility: ["SC/ST and/or Women entrepreneurs", "Age 18 years and above", "Greenfield enterprise (first-time venture)", "Non-individual enterprises with 51% shareholding by SC/ST/Women"],
        documents: ["Aadhaar Card", "Caste Certificate (for SC/ST)", "Business Plan", "Address Proof", "Bank Account"],
        applicationLink: "https://www.standupmitra.in",
        isCentral: true,
        minAge: 18,
        categoryReq: ["SC", "ST"],
        genderReq: "All",
    },
    {
        title: "PM SVANidhi - Street Vendor's AtmaNirbhar Nidhi",
        department: "Ministry of Housing & Urban Affairs",
        ministry: "Ministry of Housing & Urban Affairs",
        benefit: "Working capital loan for street vendors",
        benefitAmount: "₹10,000 - ₹50,000",
        category: ["Business", "Self-Employment", "Loan", "Urban"],
        state: "All India",
        description: "Micro-credit facility for street vendors affected by COVID-19 to resume their businesses.",
        eligibility: ["Street vendors operating on or before March 24, 2020", "Vendors possessing Certificate of Vending/Letter of Recommendation", "Age 18 and above"],
        documents: ["Aadhaar Card", "Certificate of Vending", "Bank Account", "Vendor Identity Card"],
        applicationLink: "https://pmsvanidhi.mohua.gov.in",
        isCentral: true,
        minAge: 18,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Atal Pension Yojana (APY)",
        department: "Pension Fund Regulatory & Development Authority",
        ministry: "Ministry of Finance",
        benefit: "Guaranteed minimum pension after 60 years of age",
        benefitAmount: "₹1,000 - ₹5,000/month pension",
        category: ["Pension", "Savings", "Unorganized Sector"],
        state: "All India",
        description: "Government-guaranteed pension scheme for workers in the unorganized sector. Monthly pension contribution varies by age and desired pension amount.",
        eligibility: ["Indian citizen aged 18-40 years", "Must have a savings bank account", "Not income tax payer", "Not member of any statutory social security scheme"],
        documents: ["Aadhaar Card", "Bank Account", "Mobile Number"],
        applicationLink: "https://www.npscra.nsdl.co.in/scheme-details.php",
        isCentral: true,
        minAge: 18,
        maxAge: 40,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        department: "Department of Financial Services",
        ministry: "Ministry of Finance",
        benefit: "Life insurance cover of ₹2 lakh",
        benefitAmount: "₹2,00,000 life cover @ ₹436/year",
        category: ["Insurance", "Savings"],
        state: "All India",
        description: "Affordable life insurance scheme with ₹2 lakh cover for death due to any reason at very low annual premium.",
        eligibility: ["Indian citizen aged 18-50 years", "Must have bank account with Aadhaar linked", "Auto-debit consent for annual premium"],
        documents: ["Aadhaar Card", "Bank Account", "Nomination Form"],
        applicationLink: "https://financialservices.gov.in/insurance-divisions/pmjjby",
        isCentral: true,
        minAge: 18,
        maxAge: 50,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        department: "Department of Financial Services",
        ministry: "Ministry of Finance",
        benefit: "Accidental death & disability insurance",
        benefitAmount: "₹2,00,000 cover @ ₹20/year",
        category: ["Insurance", "Savings"],
        state: "All India",
        description: "Accident insurance scheme with ₹2 lakh for accidental death and full disability, ₹1 lakh for partial disability at just ₹20 annual premium.",
        eligibility: ["Indian citizen aged 18-70 years", "Must have bank account", "Aadhaar linked to bank account"],
        documents: ["Aadhaar Card", "Bank Account", "Nomination Form"],
        applicationLink: "https://financialservices.gov.in/insurance-divisions/pmsby",
        isCentral: true,
        minAge: 18,
        maxAge: 70,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== SOCIAL SECURITY =====
    {
        title: "National Social Assistance Programme (NSAP) - Old Age Pension",
        department: "Ministry of Rural Development",
        ministry: "Ministry of Rural Development",
        benefit: "Monthly pension for elderly BPL citizens",
        benefitAmount: "₹200 - ₹500/month (Central) + State top-up",
        category: ["Pension", "Senior Citizen", "BPL"],
        state: "All India",
        description: "Provides financial assistance to elderly, widows, and persons with disabilities belonging to BPL households.",
        eligibility: ["Age 60 years and above", "Belonging to BPL household", "No regular source of financial support"],
        documents: ["Aadhaar Card", "Age Proof", "BPL Card", "Bank Account"],
        applicationLink: "https://nsap.nic.in",
        isCentral: true,
        minAge: 60,
        maxIncome: 200000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Shram Yogi Maan-Dhan (PM-SYM)",
        department: "Ministry of Labour & Employment",
        ministry: "Ministry of Labour & Employment",
        benefit: "Assured pension of ₹3,000/month after 60 years",
        benefitAmount: "₹3,000/month pension",
        category: ["Pension", "Labour", "Unorganized Sector"],
        state: "All India",
        description: "Voluntary and contributory pension scheme for unorganized workers with monthly income up to ₹15,000.",
        eligibility: ["Unorganized worker aged 18-40 years", "Monthly income up to ₹15,000", "Not a member of EPFO/ESIC/NPS"],
        documents: ["Aadhaar Card", "Bank Account", "Mobile Number"],
        applicationLink: "https://maandhan.in",
        isCentral: true,
        minAge: 18,
        maxAge: 40,
        maxIncome: 180000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Vaya Vandana Yojana (PMVVY)",
        department: "Life Insurance Corporation of India",
        ministry: "Ministry of Finance",
        benefit: "Assured pension for senior citizens",
        benefitAmount: "7.4% assured return",
        category: ["Pension", "Senior Citizen", "Savings"],
        state: "All India",
        description: "Pension scheme for senior citizens providing assured return on their investment for 10 years.",
        eligibility: ["Age 60 years and above", "Investment up to ₹15 lakh", "Indian citizen"],
        documents: ["Aadhaar Card", "Age Proof", "Bank Account", "PAN Card"],
        applicationLink: "https://www.licindia.in",
        isCentral: true,
        minAge: 60,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== SKILL DEVELOPMENT =====
    {
        title: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
        department: "Ministry of Skill Development & Entrepreneurship",
        ministry: "Ministry of Skill Development & Entrepreneurship",
        benefit: "Free skill training and certification",
        benefitAmount: "Free training + ₹8,000 reward",
        category: ["Skill Development", "Youth", "Employment"],
        state: "All India",
        description: "Flagship skill development scheme enabling youth to take up industry-relevant skill training and earn a certification.",
        eligibility: ["Indian youth (school/college dropouts or unemployed)", "Age typically 15-45 years", "No prior formal skill training"],
        documents: ["Aadhaar Card", "Bank Account", "Educational Certificate (if any)"],
        applicationLink: "https://www.pmkvyofficial.org",
        isCentral: true,
        minAge: 15,
        maxAge: 45,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "PM Vishwakarma Yojana",
        department: "Ministry of Micro, Small & Medium Enterprises",
        ministry: "Ministry of MSME",
        benefit: "Skill training, toolkit, and credit support for artisans",
        benefitAmount: "Loan up to ₹3,00,000 + free toolkit",
        category: ["Skill Development", "Business", "Artisan"],
        state: "All India",
        description: "End-to-end support for traditional artisans and craftspeople through skill training, toolkit assistance, credit support, and market linkage.",
        eligibility: ["Traditional artisans and craftspeople", "Working with hands and tools in 18 specified trades", "Age 18 years and above"],
        documents: ["Aadhaar Card", "Bank Account", "Trade-specific Certificate"],
        applicationLink: "https://pmvishwakarma.gov.in",
        isCentral: true,
        minAge: 18,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "National Apprenticeship Training Scheme (NATS)",
        department: "Ministry of Education",
        ministry: "Ministry of Education",
        benefit: "Stipend-based on-the-job training",
        benefitAmount: "₹5,000 - ₹9,000/month stipend",
        category: ["Skill Development", "Youth", "Employment"],
        state: "All India",
        description: "On-the-job practical training for graduates and diploma holders in engineering and technology.",
        eligibility: ["Graduate or diploma holder in engineering/technology", "Not employed in any organization", "Age below 30 years"],
        documents: ["Aadhaar Card", "Degree/Diploma Certificate", "Bank Account"],
        applicationLink: "https://portal.mhrdnats.gov.in",
        isCentral: true,
        maxAge: 30,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== RURAL DEVELOPMENT =====
    {
        title: "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)",
        department: "Ministry of Rural Development",
        ministry: "Ministry of Rural Development",
        benefit: "Skill training and placement for rural youth",
        benefitAmount: "Free training + placement guarantee",
        category: ["Skill Development", "Rural", "Youth", "Employment"],
        state: "All India",
        description: "Placement-linked skill development program for rural poor youth aged 15-35 from BPL families.",
        eligibility: ["Rural youth aged 15-35", "From BPL or marginally above BPL families", "SC/ST/Women/PwD/Minority priority"],
        documents: ["Aadhaar Card", "BPL Certificate", "Age Proof", "Bank Account"],
        applicationLink: "https://ddugky.gov.in",
        isCentral: true,
        minAge: 15,
        maxAge: 35,
        maxIncome: 300000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Pradhan Mantri Gram Sadak Yojana (PMGSY)",
        department: "Ministry of Rural Development",
        ministry: "Ministry of Rural Development",
        benefit: "All-weather road connectivity to unconnected habitations",
        benefitAmount: "Infrastructure development",
        category: ["Rural", "Infrastructure"],
        state: "All India",
        description: "Provides all-weather road connectivity to unconnected rural habitations with population of 500+ (250+ in hilly/tribal areas).",
        eligibility: ["Unconnected rural habitations", "Population of 500+ (250+ for hilly/tribal areas)"],
        documents: [],
        applicationLink: "https://pmgsy.nic.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Swachh Bharat Mission - Gramin",
        department: "Ministry of Jal Shakti",
        ministry: "Ministry of Jal Shakti",
        benefit: "Financial assistance for construction of household toilets",
        benefitAmount: "₹12,000 per household",
        category: ["Rural", "Sanitation", "Health"],
        state: "All India",
        description: "Aims to achieve universal sanitation coverage by providing financial incentive for toilet construction in rural areas.",
        eligibility: ["Households without access to toilet facilities", "Identified by Gram Panchayat", "BPL and above poverty line families eligible"],
        documents: ["Aadhaar Card", "BPL Card (if applicable)", "Bank Account", "Photo of household"],
        applicationLink: "https://swachhbharatmission.gov.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Jal Jeevan Mission",
        department: "Ministry of Jal Shakti",
        ministry: "Ministry of Jal Shakti",
        benefit: "Piped drinking water supply to every rural household",
        benefitAmount: "55 liters per capita per day",
        category: ["Rural", "Water", "Infrastructure"],
        state: "All India",
        description: "Aims to provide functional household tap connection to every rural household by 2024, ensuring potable water supply.",
        eligibility: ["All rural households without tap water connection"],
        documents: [],
        applicationLink: "https://jaljeevanmission.gov.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== SC/ST WELFARE =====
    {
        title: "Post-Matric Scholarship for SC Students",
        department: "Department of Social Justice & Empowerment",
        ministry: "Ministry of Social Justice & Empowerment",
        benefit: "Full tuition fee and maintenance allowance",
        benefitAmount: "Full fees + ₹550-1,200/month",
        category: ["Education", "SC", "Student"],
        state: "All India",
        description: "Provides financial assistance to SC students studying at post-matriculation level to complete their education.",
        eligibility: ["Belonging to Scheduled Caste", "Family income below ₹2.5 lakh per annum", "Enrolled in post-matric course at recognized institution"],
        documents: ["Caste Certificate", "Income Certificate", "Aadhaar Card", "Previous Marksheet", "Admission Proof"],
        applicationLink: "https://scholarships.gov.in",
        isCentral: true,
        maxIncome: 250000,
        categoryReq: ["SC"],
        genderReq: "All",
    },
    {
        title: "Pre-Matric Scholarship for ST Students",
        department: "Ministry of Tribal Affairs",
        ministry: "Ministry of Tribal Affairs",
        benefit: "Scholarship for tribal students in Class I-X",
        benefitAmount: "₹150 - ₹350/month + books",
        category: ["Education", "ST", "Student"],
        state: "All India",
        description: "Financial support to ST students studying in pre-matric classes to reduce dropout rates and promote education.",
        eligibility: ["Belonging to Scheduled Tribe", "Studying in Class I to X", "Family income below ₹2.5 lakh per annum"],
        documents: ["Tribal Certificate", "Income Certificate", "Aadhaar Card", "School Certificate"],
        applicationLink: "https://scholarships.gov.in",
        isCentral: true,
        maxIncome: 250000,
        maxAge: 18,
        categoryReq: ["ST"],
        genderReq: "All",
    },
    {
        title: "Venture Capital Fund for SC Entrepreneurs",
        department: "Department of Social Justice & Empowerment",
        ministry: "Ministry of Social Justice & Empowerment",
        benefit: "Concessional finance for SC entrepreneurs",
        benefitAmount: "Up to ₹15 crore",
        category: ["Business", "SC", "Loan"],
        state: "All India",
        description: "Provides concessional finance to SC entrepreneurs to promote and support their business ventures.",
        eligibility: ["SC entrepreneur with viable project", "Minimum 51% SC ownership", "Project should be in growth sectors"],
        documents: ["Caste Certificate", "Business Plan", "Aadhaar Card", "PAN Card", "Company Registration"],
        applicationLink: "https://socialjustice.gov.in",
        isCentral: true,
        categoryReq: ["SC"],
        genderReq: "All",
    },

    // ===== STATE-SPECIFIC SCHEMES =====
    {
        title: "Ladli Behna Yojana",
        department: "Women & Child Development Department",
        ministry: "Government of Madhya Pradesh",
        benefit: "Monthly financial assistance to 21-60 age women",
        benefitAmount: "₹1,250/month",
        category: ["Women", "Social Security"],
        state: "Madhya Pradesh",
        description: "Monthly financial assistance of ₹1,250 to women of age 21-60 belonging to lower and middle-income families.",
        eligibility: ["Women aged 21-60 years", "Resident of Madhya Pradesh", "Family income below ₹2.5 lakh per annum", "Not an income tax payer"],
        documents: ["Aadhaar Card", "Samagra ID", "Bank Account", "Passport Photo"],
        applicationLink: "https://ladlibahna.mp.gov.in",
        isCentral: false,
        minAge: 21,
        maxAge: 60,
        maxIncome: 250000,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "Majhi Ladki Bahin Yojana",
        department: "Women & Child Development Department",
        ministry: "Government of Maharashtra",
        benefit: "Monthly stipend for women",
        benefitAmount: "₹1,500/month",
        category: ["Women", "Social Security"],
        state: "Maharashtra",
        description: "Monthly financial assistance to women from economically weaker sections in Maharashtra for empowerment and self-reliance.",
        eligibility: ["Women aged 21-65 years", "Resident of Maharashtra", "Family income below ₹2.5 lakh per annum"],
        documents: ["Aadhaar Card", "Domicile Certificate", "Income Certificate", "Bank Account"],
        applicationLink: "https://womenchild.maharashtra.gov.in",
        isCentral: false,
        minAge: 21,
        maxAge: 65,
        maxIncome: 250000,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "YSR Cheyutha",
        department: "Women Development & Child Welfare",
        ministry: "Government of Andhra Pradesh",
        benefit: "Financial assistance for women aged 45-60 from BC/SC/ST/Minority",
        benefitAmount: "₹18,750/year",
        category: ["Women", "Social Security", "SC", "ST", "OBC"],
        state: "Andhra Pradesh",
        description: "Annual financial assistance to women from marginalized communities between 45-60 years of age.",
        eligibility: ["Women aged 45-60 years", "Belonging to BC/SC/ST/Minority", "Resident of Andhra Pradesh", "Family income below ₹10 lakh"],
        documents: ["Aadhaar Card", "Caste Certificate", "Age Proof", "Bank Account"],
        applicationLink: "https://navasakam.ap.gov.in",
        isCentral: false,
        minAge: 45,
        maxAge: 60,
        maxIncome: 1000000,
        genderReq: "Female",
        categoryReq: ["SC", "ST", "OBC", "Minority"],
    },
    {
        title: "Kalia Yojana",
        department: "Department of Agriculture",
        ministry: "Government of Odisha",
        benefit: "Financial assistance for farmers and landless laborers",
        benefitAmount: "₹10,000/year",
        category: ["Farmer", "Agriculture"],
        state: "Odisha",
        description: "Financial assistance to small and marginal farmers and landless agricultural laborers for cultivation and livelihood support.",
        eligibility: ["Small and marginal farmers of Odisha", "Landless agricultural laborers", "Not an income tax payer"],
        documents: ["Aadhaar Card", "Land Records (if farmer)", "Bank Account", "Ration Card"],
        applicationLink: "https://kalia.odisha.gov.in",
        isCentral: false,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Rythu Bandhu Scheme",
        department: "Department of Agriculture",
        ministry: "Government of Telangana",
        benefit: "Investment support for agriculture",
        benefitAmount: "₹10,000/acre/year",
        category: ["Farmer", "Agriculture"],
        state: "Telangana",
        description: "Direct investment support of ₹10,000 per acre per year to all land-owning farmers for purchasing farm inputs.",
        eligibility: ["Land-owning farmer in Telangana", "Land records must be updated", "All farm sizes eligible"],
        documents: ["Aadhaar Card", "Land Passbook (Pattadar)", "Bank Account"],
        applicationLink: "https://rythubandhu.telangana.gov.in",
        isCentral: false,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== DIGITAL & FINANCIAL INCLUSION =====
    {
        title: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
        department: "Department of Financial Services",
        ministry: "Ministry of Finance",
        benefit: "Zero-balance bank account with RuPay debit card",
        benefitAmount: "Free account + ₹2 lakh insurance",
        category: ["Financial Inclusion", "Banking"],
        state: "All India",
        description: "Financial inclusion program providing universal access to banking, insurance, and pension facilities.",
        eligibility: ["Any Indian citizen aged 10 years and above", "Not having a bank account", "Document verification through Aadhaar or voter ID"],
        documents: ["Aadhaar Card or Voter ID", "Passport Size Photo"],
        applicationLink: "https://pmjdy.gov.in",
        isCentral: true,
        minAge: 10,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Digital India Programme - PMGDISHA",
        department: "Ministry of Electronics & IT",
        ministry: "Ministry of Electronics & IT",
        benefit: "Free digital literacy training",
        benefitAmount: "Free training course",
        category: ["Digital Literacy", "Rural", "Education"],
        state: "All India",
        description: "Making 6 crore rural households digitally literate by training one member from every eligible household.",
        eligibility: ["One person per household (rural areas)", "Age 14-60 years", "Not digitally literate"],
        documents: ["Aadhaar Card", "Age Proof"],
        applicationLink: "https://www.pmgdisha.in",
        isCentral: true,
        minAge: 14,
        maxAge: 60,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== FOOD SECURITY =====
    {
        title: "National Food Security Act (NFSA) / Ration Card",
        department: "Department of Food & Public Distribution",
        ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
        benefit: "Subsidized food grains through PDS",
        benefitAmount: "Rice ₹3/kg, Wheat ₹2/kg, Coarse grains ₹1/kg",
        category: ["Food Security", "BPL"],
        state: "All India",
        description: "Provides subsidized food grains to approximately two-thirds of India's population under Targeted Public Distribution System.",
        eligibility: ["BPL/AAY/Priority households", "Not an income tax payer", "Identified by state government databases"],
        documents: ["Aadhaar Card", "Income Certificate", "Address Proof", "Family Details"],
        applicationLink: "https://nfsa.gov.in",
        isCentral: true,
        maxIncome: 300000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "PM Garib Kalyan Anna Yojana (PMGKAY)",
        department: "Department of Food & Public Distribution",
        ministry: "Ministry of Consumer Affairs",
        benefit: "Free food grains to NFSA beneficiaries",
        benefitAmount: "5 kg free food grains/person/month",
        category: ["Food Security", "BPL"],
        state: "All India",
        description: "Free ration scheme providing 5 kg of food grains per person per month to all NFSA beneficiaries.",
        eligibility: ["Existing NFSA/Ration card holders", "Antyodaya Anna Yojana (AAY) families", "Priority household (PHH) families"],
        documents: ["Ration Card", "Aadhaar Card"],
        applicationLink: "https://nfsa.gov.in",
        isCentral: true,
        maxIncome: 300000,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== DISABILITY & WELFARE =====
    {
        title: "Assistance to Disabled Persons (ADIP Scheme)",
        department: "Department of Empowerment of Persons with Disabilities",
        ministry: "Ministry of Social Justice & Empowerment",
        benefit: "Free assistive devices and aids for disabled persons",
        benefitAmount: "Free devices worth ₹10,000+",
        category: ["Disability", "Health"],
        state: "All India",
        description: "Provides free assistive devices like wheelchairs, hearing aids, prosthetics, and braille kits to persons with disabilities.",
        eligibility: ["40% or more disability certified", "Monthly income up to ₹20,000", "Indian citizen"],
        documents: ["Disability Certificate", "Aadhaar Card", "Income Certificate", "Bank Account"],
        applicationLink: "https://www.disabilityaffairs.gov.in",
        isCentral: true,
        maxIncome: 240000,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Indira Gandhi National Disability Pension Scheme",
        department: "Ministry of Rural Development",
        ministry: "Ministry of Rural Development",
        benefit: "Monthly pension for BPL persons with severe disability",
        benefitAmount: "₹300/month (18-79) / ₹500/month (80+)",
        category: ["Disability", "Pension", "BPL"],
        state: "All India",
        description: "Monthly pension for persons with severe and multiple disabilities (80%+) belonging to BPL households.",
        eligibility: ["80% or more disability", "Age 18 years and above", "BPL household", "Not receiving any other pension"],
        documents: ["Disability Certificate", "Aadhaar Card", "BPL Card", "Bank Account"],
        applicationLink: "https://nsap.nic.in",
        isCentral: true,
        minAge: 18,
        maxIncome: 200000,
        categoryReq: [],
        genderReq: "All",
    },

    // ===== ENERGY & INFRASTRUCTURE =====
    {
        title: "Pradhan Mantri Ujjwala Yojana (PMUY)",
        department: "Ministry of Petroleum & Natural Gas",
        ministry: "Ministry of Petroleum & Natural Gas",
        benefit: "Free LPG connection to BPL women",
        benefitAmount: "Free LPG connection + subsidy",
        category: ["Energy", "Women", "BPL", "Rural"],
        state: "All India",
        description: "Provides deposit-free LPG connections to women from BPL households for clean cooking fuel access.",
        eligibility: ["Women from BPL households", "No existing LPG connection in household", "SECC-2011 database beneficiary"],
        documents: ["Aadhaar Card", "BPL Certificate", "Ration Card", "Bank Account", "Passport Photo"],
        applicationLink: "https://www.pmujjwalayojana.com",
        isCentral: true,
        maxIncome: 200000,
        genderReq: "Female",
        categoryReq: [],
    },
    {
        title: "PM Surya Ghar - Muft Bijli Yojana",
        department: "Ministry of New & Renewable Energy",
        ministry: "Ministry of New & Renewable Energy",
        benefit: "Subsidy for rooftop solar installation",
        benefitAmount: "Up to ₹78,000 subsidy",
        category: ["Energy", "Housing", "Subsidy"],
        state: "All India",
        description: "Provides central financial assistance for installation of rooftop solar panels enabling households to get free electricity.",
        eligibility: ["Residential households with suitable rooftop", "Valid electricity connection", "Not previously availed subsidy for rooftop solar"],
        documents: ["Aadhaar Card", "Electricity Bill", "Property Documents", "Bank Account", "Photo of Rooftop"],
        applicationLink: "https://pmsuryaghar.gov.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },
    {
        title: "Saubhagya - Pradhan Mantri Sahaj Bijli Har Ghar Yojana",
        department: "Ministry of Power",
        ministry: "Ministry of Power",
        benefit: "Free electricity connections to all unelectrified households",
        benefitAmount: "Free electricity connection",
        category: ["Energy", "BPL", "Rural"],
        state: "All India",
        description: "Provides free electricity connections to all remaining un-electrified households in rural and urban areas.",
        eligibility: ["Households without electricity connection", "Poor households (BPL) get free connection", "Others can avail at subsidized cost"],
        documents: ["Aadhaar Card", "Address Proof", "BPL Card (if applicable)"],
        applicationLink: "https://saubhagya.gov.in",
        isCentral: true,
        categoryReq: [],
        genderReq: "All",
    },
];

async function main() {
    console.log('🌱 Starting seed...');
    console.log(`📋 Seeding ${schemes.length} Indian government schemes...`);

    // Clear existing schemes
    await prisma.scheme.deleteMany();
    console.log('🗑️  Cleared existing schemes');

    // Insert all schemes
    for (const scheme of schemes) {
        await prisma.scheme.create({
            data: {
                title: scheme.title,
                department: scheme.department,
                ministry: scheme.ministry,
                benefit: scheme.benefit,
                benefitAmount: scheme.benefitAmount || null,
                category: scheme.category,
                state: scheme.state,
                description: scheme.description,
                eligibility: scheme.eligibility,
                documents: scheme.documents,
                applicationLink: scheme.applicationLink,
                isCentral: scheme.isCentral,
                minAge: scheme.minAge || null,
                maxAge: scheme.maxAge || null,
                maxIncome: scheme.maxIncome || null,
                genderReq: scheme.genderReq || "All",
                categoryReq: scheme.categoryReq || [],
            },
        });
    }

    console.log(`✅ Seeded ${schemes.length} schemes successfully!`);
    console.log('\nCategories covered:');
    const categories = [...new Set(schemes.flatMap(s => s.category))];
    categories.forEach(c => console.log(`  • ${c}`));
}

main()
    .catch((e) => {
        console.error('❌ Seed error:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
